### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by TiRajo** [xhlove/WVGuesser#1]
Error while finding module specification for 'wvguesser.main' (ModuleNotFoundError: No module named 'wvguesser') am geting this

**Comment by xbstory** [comment]
use exe version, just drop config file to exe, and it will work.
![oCam_2021_07_30_20_58_41_915](https://user-images.githubusercontent.com/48152166/127658025-ea37fef7-1551-47c5-a4b1-50f3341dd123.gif)

**Comment by TiRajo** [comment]
Ok i got the exe file Thanks for It ! Wow Your
