### ISSUE TITLE
不支持friday.tw

### ISSUE THREAD

**Issue by kedyao** [xhlove/WVGuesser#2]
friday打开播放页面无反应

**Comment by xbstory** [comment]
https://github.com/Satsuoni/widevine-l3-guesser

这个插件有输出吗，如果也没有可能就是没有吧。。

**Comment by kedyao** [comment]
原始插件也无输出

**Comment by xbstory** [comment]
既然原插件也不行，我也不太清楚了

**Comment by chengrui146** [comment]
friday都没加密了，当然不会输出 @kedyao

**Comment by kedyao** [comment]
我收集的key  VOICE II ～110緊急指令室～ friday 第1集 c5e0c1b32377497389f4d7a17834b75a:c0d8f82e1ea2d6f3efc6ad7337c18afd
依然使用MP4DecryptGUI进行解密

**Comment by chengrui146** [comment]
现在friday就是时不时的上加密
指不定明天去看又是上加密的状态
现在是mpd和m3u8直接没加密 @kedyao
