### ISSUE TITLE
 卡著 99.x0%

### ISSUE THREAD

**Issue by qoo8888** [xhlove/WVGuesser#7]
HI ,
同一个影片video 几个JSON都是卡着 99.X0%

请帮忙,谢谢

**Comment by xbstory** [comment]
直接用原项目插件吧，秒出key

**Comment by qoo8888** [comment]
是吗? 用过没有反应,chrome console,没有看见content_key_decryption.js
其他GITHUB旧版本都用到但看不到KEY,
再试了https://bitmovin.com/demos/drm,  一样看不到KEY, 请指教,谢谢

**Comment by xbstory** [comment]
你可能插件没装好吧，先把之前的相关插件禁用，然后再从本地加载下

可以试试这个版本

https://github.com/nilaoda/widevine-l3-guesser/tree/modified

**Comment by qoo8888** [comment]
謝謝,都是不能


原来出了以下error
Uncaught SyntaxError: Cannot use 'import.meta' outside a module

堆叠追踪
wasm/wasm_gsr.js:3 (匿名函式)

>>>>var _scriptDir = import.meta.url;

**Comment by xbstory** [comment]
没见过你这种情况，，估计你浏览器有问题，重新下一个吧
